### ISSUE TITLE
Advanced scheduler enabled/disabled self toggles

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#155]
I noticed the toggle for the enabled / disabled state of a schedule can be toggled, then the schedule is modified and saved (without refreshing the page), and the toggle will flip itself back!

**Comment by jazdw** [comment]
This is because enabled/disabled is a property of a schedule, when you start editing a schedule you get a snapshot of its properties at that point in time. Its basically happens because of simultaneous edits. We should probably just show an input for enabled/disabled on the editing side of the page.
